App\Entity\Word:
  type: entity
  repositoryClass: App\Repository\WordRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options:
        unsigned: true
  fields:
    letters:
      type: string
      length: 10